### ISSUE TITLE
OBS not opening

### ISSUE THREAD

**Issue by guiray** [pkviet/obs-asio#2]
OBS 21.1.2 is not opening with that plugin installed. It starts correctly if I uninstall the plugin.

Have you seen that before?

**Comment by pkviet** [comment]
which version of the plugin v1 or v2 ?

**Comment by pkviet** [comment]
i observe no issues with plugin v1 with obs 21.1.2
![capture](https://user-images.githubusercontent.com/9283407/42651006-57199cc4-860e-11e8-81c1-223a4226bb61.PNG)

what is your sound device ?

**Comment by CHEF-KOCH** [comment]
I'm using v2 with 21.1.2 and can confirm it (still) works well. I think the 'not opening' is related to a crash or memory leak, maybe caused by other installed plugins or in combination with a wrong configuration. 

The thread opener doesn't provide any useful information or OBS log so it's only speculation.

**Comment by pkviet** [comment]
thanks for checking with v2 @CHEF-KOCH 
I would need a log to do more troubleshooting

**Comment by guiray** [comment]
I tried with v1 just before the weekend. I will re-test again and provide with more infos if it happens again. Thank you for checking or you side!

**Comment by guiray** [comment]
So before installing the plugin, OBS starts without any problems. After installing the plugin v1, nothing happens when launching OBS.

Here is the log: https://pastebin.com/raw/ySeWaR8p
Sound device is ASIO4ALL

I'm not familiar with logs, but it seems that some files are missing on my system. Not sure if it's obs-asio retalted or not though.

Btw sorry for the lack of details opening the thread.

**Comment by CHEF-KOCH** [comment]
There is no file missing on your system, the error OBS Studio is returning is normal because it searches for option-related files (not included due to copyright reasons) and usually only not needed cause OBS uses another library instead (if not detected). 

I only can speculate but OBS isn't running as admin so I would try to do that first. 

I'm not really sure if Asio4all works on the latest Windows OS cause MS changed several things again. I know Voicmeeter works fine and they also did some adjustments in order to fix some things. Maybe try to install it or another compatible driver but from the log, nothing much is shown, it not even shows that OBS itself is crashing so I only assume that this must come from other components which OBS tries to load and possible gets stuck then.

**Comment by guiray** [comment]
I tried running OBS as admin as well and I have the same "error" / log. The thing I find strange is that it happens only after installing the asio plugin, and when I uninstall it everything is back to normal.

I will try with an external sound card (with an asio driver), and I will try to replicate this on another pc.
Thanks a lot for your answer, reporting back soon.

**Comment by matiaspl** [comment]
This might be qt version mismatch between OBS and the plugin. I had this
very same behaviour with obs-websocket on a Mac. Try running OBS from
command line (or check the logs).


Matt

pon., 16.07.2018, 17:25 użytkownik Guillaume Raymond <
notifications@github.com> napisał:

**Comment by pkviet** [comment]
@guiray
it would be easier to troubleshoot "live" on discord for instance  https://discordapp.com/invite/obsproject
ping me there (@pkv) . I should be around.

Your log entries are ok. The crash is during the dll loading. But I can't pinpoint what's going on with your install.
Maybe you have other plugins and there is a conflict. I doubt there is a Qt issue because I was able to run the plugin with obs 21.1.2 unlike you. So we must look into your local install.

In the meantime, I have two suggestions:
1) complete uninstall and reinstall; make sure the Program folder is erased completely so that there is no other plugin left and asio is the only one.
2) erase the following folder: C:\Users\your_name\AppData\Roaming\obs-studio

**Comment by guiray** [comment]
@pkviet I tried your suggestions and no go, still nothing is happening. There is no process showing up in Task Manager as well.

the last log line is:
`14:00:51.509: Failed to initialize module 'enc-amf.dll'`

I tried on an other machine and it works like a charm, so it's my local install like you said. The message just after the last one I have on the previous machine about the asio plugin:
`14:12:40.560: Failed to initialize module 'enc-amf.dll'`
`14:12:40:619: asio-input: ASIO Devices: 1`

Does obs-asio rely on some files? I really don't know what is going on, maybe some files missing, or an application blocking that specific plugin, antivirus by example (obs act the same way while my antivirus is disable).

I'll try to poke you on discord next week. 
Thank you

**Comment by pkviet** [comment]
Yes the plugin depends on portaudio library which is installed with the obs-asio dll.
It might be the antivirus... Try to disable it to see if it solves things. Worth trying at any rate.

**Comment by thelivingdiamond** [comment]
Was there ever any solution reached?

**Comment by Andersama** [comment]
There have been several bugs patched since this issue was opened, if you're still having this issue w/ the current version, please let us know.

**Comment by thelivingdiamond** [comment]
I am having this issue currently. It happens on v 22.0.x and 21.1.2 of obs, with version 1.0, 1.1, 1.2 and 1.3 of obs asio (applied to the respective versions of obs. Prior to installing the add-on, obs studio runs perfectly. As soon as I use the installer however (I was too tired to compile it on my own) obs studio refused to start. Watching the process in task manager it starts, and then just stops. After using the built in obs-asio uninstaller, however, obs functions fine. I tried almost everything in this thread. I'm a little stuck

**Comment by pkviet** [comment]
what is your device ? do you have a crash log ? you can ping either of us on discord if you want to discuss your issue in more depth
