### ISSUE TITLE
Bassasio compile share

### ISSUE THREAD

**Issue by jbehrmusic** [pkviet/obs-asio#20]
hello. i figured out how to compile the bassasio properly. I know you have stated that you aren't allowed to share it, per some condition or contract. but since I am not the developer, am I allowed to share it? Many people in the music community have been having these same issues for years, with Windows  and ASIO drivers. But this bassasio compile made everything 100 times easier, and I wanted to create a youtube tutorial and share it with people. May I do that?

**Comment by pkviet** [comment]
Nope. You aren't allowed to share the binaries because bassasio license is
not compatible with obs-studio license and would be in violation of GPL v2.
The terms apply to any user not just the developper.
If however you want to make a video tutorial though, you can.

**Comment by jbehrmusic** [comment]
I am a little confused. I am allowed to make a video tutorial on how I compiled it?

**Comment by pkviet** [comment]
yes you can make a video tutorial.
obs-studio is released under gpl v2+ which implies that any plugin linking to obs can't be released if its whole source code is not released.
bassasio is not released with its source code, that's why its license is not compatible with gpl v2 and why we don't release our plugin.

**Comment by jbehrmusic** [comment]
I am in contact with Ian Luck from un4seen.com, and he said it is fine for me and other people to use BASSASIO personally without a license. I ask for clarification whether that means I can share it or not.

**Comment by pkviet** [comment]
FYI, check the wiki page: https://github.com/pkviet/obs-asio/wiki/Compilation-instructions
I now provide obs.dll and obs.lib so it's not necessary to compile obs-studio; this speeds the compilation time of course.

**Comment by jbehrmusic** [comment]
According to Ian Luck (at un4seen.com), I can share the BASSASIO.DLL that I compiled myself, as long as I am not a company or I am making profit from it. Which, both are true. I won't be selling it, or using it as a company, so I believe I am able to share it, correct?

**Comment by pkviet** [comment]
> According to Ian Luck (at un4seen.com), I can share the BASSASIO.DLL that I compiled myself, as long as I am not a company or I am making profit from it. Which, both are true. I won't be selling it, or using it as a company, so I believe I am able to share it, correct?

you misunderstood him and he misunderstood you.
You are NOT compiling bassasio.dll : the bassasio.dll is distributed by Ian Luck, it's already compiled. You don't have his code for bassasio , how could you compile the dll ?
What you are compiling is obs-asio.dll which depends on bassasio library with a dynamical linkage (it loads bassasio.dll).
Is it clear ?
You are NOT allowed to distribute obs-asio.dll that you compiled. This is due to the license conflict between bassasio, obs-studio and asio sdk.
I'm an individual and non profit; if these were enough conditions to distribute obs-asio.dll (bassasio version) I would do it readily.
The only obs-asio.dll we're allowed to release is the version relying on portaudio and our opensource asio sdk.
Ping me on obs-studio discord if you need further explanation.

**Comment by pkviet** [comment]
closing, since the answer is clear:
obs-asio.dll with linkage to bassasio.dll CAN'T be distributed.
this is a license issue, about which we can't do anything unless bassasio becomes GPL v2 compatible, which it is NOT
